### PR TITLE
README: Add FlapJob addr

### PR DESCRIPTION
**Pull request by sunbreak1211**

### CODE REVIEW

**Review by oldchili — APPROVED** [review]
Code matches repo.
Deployment params look good.
Constructor params ok.

**Review by hexonaut — COMMENTED** [review]
You want to leave the spaces at the end so it inserts a newline.

**Comment by sunbreak1211** [comment]
> You want to leave the spaces at the end so it inserts a newline.

thanks, fixed!

**Review by hexonaut — APPROVED** [review]
LGTM

**Pull request merged**
